[package]
name = "checkmark_lint_common"
description = "Internal crate that provides types needed for linter"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
markdown.workspace = true
common.workspace = true
url.workspace = true
